physics: 
  refresh_rate: 0.02 # This is in ms 1/rate = hz
  mass: 10 # kg
  g: 9.81 # Gravity Constant
  k: 0.25 # Drag Coefficient

force_model:
  input_dim: 16
  hidden_layers: 3
  hidden_size: 128
  output_dim: 9
  state_dim: 12

training: 
  num_epochs: 50
  batch_size: 256
  lr: 0.01
  seq_len: 2